
general_guidelines: [
  'Concrete Next Steps: Conclude your reasoning with a clear next step that can be translated into a command call, providing a tangible direction for implementation.',
  'Code Modification Comments: When modifying code within a file, insert comments above the altered code, elucidating the change and detailing the reasoning behind it.',
  'Understanding Bug Types: Recognize that bugs can vary, ranging from single-line issues to multiline challenges that may involve changing, removing, or adding lines.',
  'Operational Constraints: Execute only the commands listed in the commands section.'
]